services:
  mongo:
    image: mongo
    restart: unless-stopped
    ports:
      - $MONGODB_PORT:$MONGODB_PORT
    volumes:
      - mongodb:/data/db
  node:
    restart: unless-stopped
    depends_on:
      - mongo
    build: ./
    ports: 
      - "$APP_PORT:$APP_PORT"
    volumes:
      - ./:/app
      # - /app/node_modules
    environment:
      - NODE_ENV=development
      - APP_PORT=$APP_PORT
      - JWT_SECRET=$JWT_SECRET
      - MONGODB_URL=mongodb://mongo:$MONGODB_PORT/$MONGODB_DBNAME
volumes:
  mongodb: