services:
  mongodb_carstory:
    image: mongo:4.4.6
    restart: unless-stopped
    ports:
      - $MONGODB_PORT:$MONGODB_PORT
    volumes:
      - mongodb:/data/db
    environment:
      - MONGO_INITDB_DATABASE=$MONGODB_DBNAME
      - MONGO_INITDB_ROOT_USERNAME=$MONGODB_USER
      - MONGO_INITDB_ROOT_PASSWORD=$MONGODB_PASSWORD
    container_name: mongodb.api.carstory.mdomzalski.pl
  api_carstory:
    restart: unless-stopped
    env_file:
      - ./.env
    depends_on:
      - mongodb_carstory
    build: ./
    command: npm run prod
    expose:
      - $APP_PORT
    volumes:
      - /app/node_modules
    container_name: api.carstory.mdomzalski.pl
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api-carstory.rule=Host(`api.carstory.mdomzalski.pl`,`www.api.carstory.mdomzalski.pl`)"
      - "traefik.http.routers.api-carstory.entrypoints=websecure"
      - "traefik.http.routers.api-carstory.tls.certresolver=production"
      - "traefik.http.routers.api-carstory-https.tls=true"
      - "traefik.http.routers.api-carstory-https.rule=Host(`api.carstory.mdomzalski.pl`,`www.api.carstory.mdomzalski.pl`)"
      - "traefik.http.routers.api-carstory-https.entrypoints=websecure"
      - "traefik.http.routers.api-carstory-https.service=api-carstory"
      - "traefik.http.services.carstory.loadbalancer.server.port=80"
volumes:
  mongodb:
networks:
  default:
    name: traefik
    external: true
