services:
  mongo:
    image: mongo
    restart: unless-stopped
    ports:
      - $MONGODB_PORT:$MONGODB_PORT
    volumes:
      - mongodb:/data/db
    environment:
      - MONGO_INITDB_DATABASE=$MONGODB_DBNAME
      - MONGO_INITDB_ROOT_USERNAME=$MONGODB_USER
      - MONGO_INITDB_ROOT_PASSWORD=$MONGODB_PASSWORD
    networks:
      - carstory_express
  node:
    restart: unless-stopped
    depends_on:
      - mongo
    build: ./
    command: npm start:prod
    ports: 
      - "$APP_PORT:$APP_PORT"
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - NODE_ENV=$NODE_ENV
      - APP_PORT=$APP_PORT
      - JWT_SECRET=$JWT_SECRET
      - MONGODB_URL=$MONGODB_URL
      - VIRTUAL_HOST=$VIRTUAL_HOST
      - LETSENCRYPT_HOST=$LETSENCRYPT_HOST
    networks:
      - carstory_express
volumes:
  mongodb: